[env:esp32-s3-devkitc-1]
platform   = espressif32
board      = esp32-s3-devkitc-1
framework  = arduino
monitor_speed = 115200

board_build.flash_mode          = qio
board_build.arduino.memory_type = qio_opi
board_upload.flash_size         = 8MB
board_build.partitions          = custom_partitions.csv

build_flags =
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D NEOPIXEL_PIN=48
  -D RELAY_PIN=1
  -D GPIO1_PIN=2
  -D GPIO2_PIN=3
  -D GPIO3_PIN=4
  -D GPIO4_PIN=5
  -D FW_VERSION='"0.1.0"'
  -D FW_DATE='"2026-06-10"'

lib_deps =
  ESP Async WebServer
  AsyncMqttClient
  fastled/FastLED
  nanopb/Nanopb
  bblanchon/ArduinoJson
  lorol/LittleFS_esp32

extra_scripts =
  pre:version_inc.py
